openapi: '3.0.0'
info:
  version: 1.0.0
  title: ATSystems API
  license:
    name: MIT
servers:
  - url: http://api.atsystems.com/v1
paths:
  /traffic-sources:
    get:
      summary: List traffic sources
      operationId: listTrafficSources
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of traffic sources
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrafficSources'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create traffic source
      operationId: createTrafficSource
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /traffic-sources/{sourceId}:
    get:
      summary: Get traffic source
      operationId: getTrafficSource
      parameters:
        - name: sourceId
          in: path
          required: true
          description: The id of the traffic source to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrafficSources'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /bids:
    get:
      summary: List bids
      operationId: listBids
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of bids
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bids'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create bid
      operationId: createBid
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    TrafficSource:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        network:
          type: string
    TrafficSources:
      type: array
      items:
        $ref: '#/components/schemas/TrafficSource'
    Bid:
      required:
        - id
        - amount
      properties:
        id:
          type: integer
          format: int64
        amount:
          type: number
        sourceId:
          type: integer
          format: int64
    Bids:
      type: array
      items:
        $ref: '#/components/schemas/Bid'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string